Name: "BDClient"
Version: "1.0.0"
port: 1337
node: "game1"
DataDirectory: "./uploads"
DataFile: "data.zip"
Token: "SomerandomToken"
ServiceToken: "mysupersecretToken"
IpHeader: "default"
remote: "localhost:1337"
ssl: true